### ISSUE TITLE
src/lib/posts.js - Prism is not defined

### ISSUE THREAD

**Issue by wstabosz** [matfantinel/matfantinel.github.io#12]
## Error message:
```
Prism is not defined
ReferenceError: Prism is not defined
    at Object.<anonymous> (D:\code\matfantinel.github.io\node_modules\prism-svelte\index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (D:\code\matfantinel.github.io\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75134:17)
    at ssrImport (D:\code\matfantinel.github.io\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75076:20)
    at eval (/src/lib/posts.js:4:37)
```

## To Reproduce
The error only triggers if your `posts` folder does not contain any `md` files which use the `CodeBlock` component.

1. Delete all files `.../posts/*.md` that use the `CodeBlock` component.
2. Restart `npm run dev`

You should see the error message.

## What fixed it for me
I updated `posts.js` and added
`import Prism from 'prismjs';`
immediatly before the line
`import 'prism-svelte';`

as recommended at https://github.com/pngwn/prism-svelte

**Comment by matfantinel** [comment]
Oooh, I faced this at some point during development but it went away so I forgot about it (because I had posts with CodeBlock inside). Thanks for this! Just pushed the fix to main.
